---
- hosts: myservers
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
     name: "{{myubuntupackubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: start webservice on ubuntu
    service:
     name: "{{myubuntupackubuntu}}"
     state: started
    when: ansible_os_family=="Debian"  

  - name: install webserver on RedHat
    yum:
     name: "{{myubuntupackredhat}}"
     state: present
    when: ansible_os_family=="RedHat"

  - name: start webservice on RedHat
    service:
     name: "{{myubuntupackredhat}}"
     state: started
    when: ansible_os_family=="RedHat" 

